[book]
authors = ["David Gasquez"]
language = "en"
multilingual = false
src = "content"
title = "David Gasquez's Handbook"

[output.html]
no-section-label = true
additional-css = ["custom.css"]
default-theme = "light"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/davidgasquez/handbook"
git-repository-icon = "fa-github"
site-url = "/handbook/"
